const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('windowControls', {
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  setWindowMeta: (title, icon) => ipcRenderer.send('window:set-meta', { title, icon }),
  openThemeSettings: () => ipcRenderer.send('theme:open-settings'),
  openThemeBrowser: () => ipcRenderer.send('theme:open-browser'),
  openProfileSettings: () => ipcRenderer.send('profile:open-settings'),
  openCallWindow: state => ipcRenderer.send('call:open', state),
  updateCallWindow: state => ipcRenderer.send('call:update', state),
  closeCallWindow: () => ipcRenderer.send('call:close'),
  callAction: action => ipcRenderer.send('call:action', action),
  detachChat: chat => ipcRenderer.invoke('chat:detach', chat),
  returnChat: chat => ipcRenderer.send('chat:return', chat),
  closeDetachedChats: () => ipcRenderer.send('chat:close-all'),
  focusDetachedChat: chat => ipcRenderer.invoke('chat:focus-detached', chat),
  listThemes: () => ipcRenderer.invoke('theme:list'),
  getActiveTheme: () => ipcRenderer.invoke('theme:current'),
  previewTheme: (id, scheme) => ipcRenderer.invoke('theme:preview', id, scheme),
  applyTheme: (id, scheme) => ipcRenderer.invoke('theme:apply', id, scheme),
  importTheme: () => ipcRenderer.invoke('theme:import'),
  listCatalogThemes: () => ipcRenderer.invoke('theme:browser-list'),
  getCatalogThemeDetails: id => ipcRenderer.invoke('theme:browser-details', id),
  installCatalogTheme: id => ipcRenderer.invoke('theme:browser-install', id),
  getDisplaySettings: () => ipcRenderer.invoke('display:current'),
  applyDisplaySettings: settings => ipcRenderer.invoke('display:apply', settings),
  onThemeChanged: callback => ipcRenderer.on('theme:changed', (_, data) => callback(data)),
  onDisplayChanged: callback => ipcRenderer.on('display:changed', (_, data) => callback(data)),
  onProfileChanged: callback => ipcRenderer.on('profile:changed', (_, data) => callback(data)),
  onCallUpdate: callback => ipcRenderer.on('call:update', (_, data) => callback(data)),
  onCallAction: callback => ipcRenderer.on('call:action', (_, data) => callback(data)),
  onChatRestore: callback => ipcRenderer.on('chat:restore', (_, data) => callback(data)),
  profileChanged: user => ipcRenderer.send('profile:changed', user),
  resize: (direction, dx, dy) => ipcRenderer.send('window:resize', { direction, dx, dy })
});
